# SERVER SETTINGS
HOST: 0.0.0.0
PORT: 9000

#INITIAL SETTINGS
vocab: ./vocab/vocab.txt
pretrain: bert-base-multilingual-uncased
model: ./weights/model-state.bin
basic_infos: ["name", "date of birth", "email", "address", "gender",
                "phone", "job title"]
skill: ./configs/skill.txt
update_file: ./data/update.txt

# MODEL PARAMETERS
max_len: 500
num_labels: 12
max_grad_norm: 1.0
tags_vals: ["UNKNOWN", "O", "name", "date of birth", "email", "address", "gender",
             "phone", "job title", "education", "company name", "company position"]
resticted_lables: ["UNKNOWN", "O"]

# TRAINING
batch_size: 8
ratio_split: 0.8
lr: 3e-5
#JWT
SECURITY_ALGORITHM : 'HS256'
SECRET_KEY : '123456'